#define STATIC_TABLE_GENERATOR
#define main included_solver_main
#include "my_solver.c"
#undef main

static void print_u16_table(const char *name, const uint16_t *values,
                            size_t rows, size_t columns)
{
    printf("static const uint16_t %s[%u][%u] = {\n",
           name, (unsigned) rows, (unsigned) columns);

    for (size_t row = 0; row < rows; ++row) {
        puts("    {");

        for (size_t column = 0; column < columns; ++column) {
            if (column % 12U == 0)
                fputs("        ", stdout);

            printf("%u,", values[row * columns + column]);

            if (column % 12U == 11U || column + 1U == columns)
                putchar('\n');
            else
                putchar(' ');
        }

        puts("    },");
    }

    puts("};");
    putchar('\n');
}

static void print_u8_table(const char *name, const uint8_t *values,
                           size_t count)
{
    printf("static const uint8_t %s[%u] = {\n", name, (unsigned) count);

    for (size_t i = 0; i < count; ++i) {
        if (i % 24U == 0)
            fputs("    ", stdout);

        printf("%u,", values[i]);

        if (i % 24U == 23U || i + 1U == count)
            putchar('\n');
        else
            putchar(' ');
    }

    puts("};");
    putchar('\n');
}

static void print_asm_u16_table(const char *name, const uint16_t *values,
                                size_t count)
{
    printf(".align 1\n.globl %s\n%s:\n", name, name);

    for (size_t i = 0; i < count; ++i) {
        if (i % 12U == 0)
            fputs("    .half ", stdout);

        printf("%u", values[i]);

        if (i % 12U == 11U || i + 1U == count)
            putchar('\n');
        else
            fputs(", ", stdout);
    }

    putchar('\n');
}

static void print_asm_u8_table(const char *name, const uint8_t *values,
                               size_t count)
{
    printf(".globl %s\n%s:\n", name, name);

    for (size_t i = 0; i < count; ++i) {
        if (i % 24U == 0)
            fputs("    .byte ", stdout);

        printf("%u", values[i]);

        if (i % 24U == 23U || i + 1U == count)
            putchar('\n');
        else
            fputs(", ", stdout);
    }

    putchar('\n');
}

static void print_c_tables(void)
{
    puts("/* Generated by generate_tables.c. Do not edit manually. */");
    putchar('\n');

    print_u16_table("permutation", &permutation[0][0],
                    FACES, PERMUTATIONS);
    print_u16_table("orientation", &orientation[0][0],
                    FACES, ORIENTATIONS);
    print_u8_table("perm_dist", perm_dist, PERMUTATIONS);
    print_u8_table("ori_dist", ori_dist, ORIENTATIONS);
}

static void print_asm_tables(void)
{
    puts("# Generated by generate_tables.c. Do not edit manually.");
    puts(".data");
    putchar('\n');

    print_asm_u16_table("permutation", &permutation[0][0],
                        FACES * PERMUTATIONS);
    print_asm_u16_table("orientation", &orientation[0][0],
                        FACES * ORIENTATIONS);
    print_asm_u8_table("perm_dist", perm_dist, PERMUTATIONS);
    print_asm_u8_table("ori_dist", ori_dist, ORIENTATIONS);
}

int main(int argc, char **argv)
{
    build_transition_tables();
    build_heuristic_tables();

    if (argc == 1)
        print_c_tables();
    else if (argc == 2 && strcmp(argv[1], "--asm") == 0)
        print_asm_tables();
    else {
        fprintf(stderr, "usage: %s [--asm]\n", argv[0]);
        return 2;
    }

    return fflush(stdout) != 0 || ferror(stdout);
}
