#define STATIC_TABLE_GENERATOR
#define main included_solver_main
#include "my_solver.c"
#undef main

static void print_u16_table(const char *name, const uint16_t *values,
                            size_t rows, size_t columns)
{
    printf("static const uint16_t %s[%u][%u] = {\n",
           name, (unsigned) rows, (unsigned) columns);

    for (size_t row = 0; row < rows; ++row) {
        puts("    {");

        for (size_t column = 0; column < columns; ++column) {
            if (column % 12U == 0)
                fputs("        ", stdout);

            printf("%u,", values[row * columns + column]);

            if (column % 12U == 11U || column + 1U == columns)
                putchar('\n');
            else
                putchar(' ');
        }

        puts("    },");
    }

    puts("};");
    putchar('\n');
}

static void print_u8_table(const char *name, const uint8_t *values,
                           size_t count)
{
    printf("static const uint8_t %s[%u] = {\n", name, (unsigned) count);

    for (size_t i = 0; i < count; ++i) {
        if (i % 24U == 0)
            fputs("    ", stdout);

        printf("%u,", values[i]);

        if (i % 24U == 23U || i + 1U == count)
            putchar('\n');
        else
            putchar(' ');
    }

    puts("};");
    putchar('\n');
}

int main(void)
{
    build_transition_tables();
    build_heuristic_tables();

    puts("/* Generated by generate_tables.c. Do not edit manually. */");
    putchar('\n');

    print_u16_table("permutation", &permutation[0][0],
                    FACES, PERMUTATIONS);
    print_u16_table("orientation", &orientation[0][0],
                    FACES, ORIENTATIONS);
    print_u8_table("perm_dist", perm_dist, PERMUTATIONS);
    print_u8_table("ori_dist", ori_dist, ORIENTATIONS);

    return fflush(stdout) != 0 || ferror(stdout);
}
